{
 "title": "API Service Dashboard",
 "refresh": "5s",
 "panels": [
  {
   "title": "Logs Ingested",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "incidentiq_logs_ingested_total" }
   ]
  },
  {
   "title": "Tasks Enqueued",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "incidentiq_logs_enqueued_total" }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "process_open_fds" }
   ]
  },
  {
   "title": "Ingestion Rate (logs/sec)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 4, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "rate(incidentiq_logs_ingested_total[1m])"
    }
   ]
  },
  {
   "title": "Enqueue Rate (tasks/sec)",
   "type": "stat",
   "gridPos": { "x": 6, "y": 4, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "rate(incidentiq_logs_enqueued_total[1m])"
    }
   ]
  },
  {
   "title": "Resident Memory (MB)",
   "type": "stat",
   "gridPos": { "x": 12, "y": 4, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Logs Ingested Per Second",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "rate(incidentiq_logs_ingested_total[1m])"
    }
   ]
  },
  {
   "title": "API CPU Usage",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])"
    }
   ]
  }
 ]
}